# Generated by Django 3.0.6 on 2021-01-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': True},
        ),
    ]
