# Generated by Django 3.0.6 on 2021-01-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='featured_static/')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
