# Generated by Django 3.0.6 on 2020-10-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('offer', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=25)),
                ('descirption', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
