# Generated by Django 3.0.6 on 2020-10-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descirption',
            new_name='description',
        ),
    ]
